language: node_js
node_js:
  - "stable"

before_script:
  - npm i

script:
  - npm run eslint
  - npm run test

cache:
  directories:
    - node_modules

notifications:
  slack:
    rooms:
      - touno-io:bAvs98HimZWCvolKDxgPwxEn
    on_success: change
    on_failure: always
